products = [
    {
        'id': '1',
        'name': 'Set de couverts inox 24 pièces',
        'image': '/media/products/set-couverts-inox-24.png',
        'description': 'Un ensemble complet de couverts en acier inoxydable pour 6 personnes.',
        'brand': 'SimpleCulinary',
        'category': 'Couverts',
        'price': 299,
        'countInStock': 10,
    },
    {
        'id': '2',
        'name': 'Set de couteaux de table 6 pièces',
        'image': '/media/products/set-couteaux-table-6.png',
        'description': 'Des couteaux élégants et résistants pour les repas quotidiens.',
        'brand': 'SimpleCulinary',
        'category': 'Couteaux',
        'price': 149,
        'countInStock': 10,
    },
    {
        'id': '3',
        'name': 'Ménagère dorée 16 pièces',
        'image': '/media/products/menagere-doree-16.png',
        'description': 'Un set de couverts dorés au design moderne pour une table raffinée.',
        'brand': 'SimpleCulinary',
        'category': 'Couverts premium',
        'price': 399,
        'countInStock': 10,
    },
    {
        'id': '4',
        'name': 'Set de cuillères à dessert 12 pièces',
        'image': '/media/products/set-cuilleres-dessert-12.png',
        'description': 'Des cuillères pratiques pour desserts, cafés et goûters.',
        'brand': 'SimpleCulinary',
        'category': 'Cuillères',
        'price': 99,
        'countInStock': 10,
    },
    {
        'id': '5',
        'name': 'Set de fourchettes inox 12 pièces',
        'image': '/media/products/set-fourchettes-inox-12.png',
        'description': 'Des fourchettes solides et faciles à nettoyer pour un usage quotidien.',
        'brand': 'SimpleCulinary',
        'category': 'Fourchettes',
        'price': 119,
        'countInStock': 10,
    },
    {
        'id': '6',
        'name': 'Couverts enfants colorés 4 pièces',
        'image': '/media/products/couverts-enfants-colores-4.png',
        'description': 'Un petit set sécurisé et coloré adapté aux enfants.',
        'brand': 'SimpleCulinary',
        'category': 'Enfants',
        'price': 79,
        'countInStock': 10,
    },
]
